"""PDF report generation with charts and tables.

Uses a lightweight HTML-to-PDF approach for generating research reports.

Requirements: 35.6
"""

from __future__ import annotations

import io
import logging
from typing import Any

logger = logging.getLogger(__name__)


class PDFGenerator:
    """Generates PDF reports from structured data.

    Uses a simple HTML template approach. For production, consider
    weasyprint or reportlab for richer formatting.
    """

    def generate_factor_snapshot_pdf(self, data: Any) -> bytes:
        """Generate PDF for weekly factor snapshot."""
        html = self._render_factor_snapshot_html(data)
        return self._html_to_pdf(html)

    def generate_sector_deepdive_pdf(self, data: Any) -> bytes:
        """Generate PDF for monthly sector deep-dive."""
        html = self._render_sector_deepdive_html(data)
        return self._html_to_pdf(html)

    def _render_factor_snapshot_html(self, data: Any) -> str:
        """Render factor snapshot as HTML."""
        rows = ""
        for f in getattr(data, "factors", []):
            rows += (
                f"<tr><td>{f.name}</td>"
                f"<td>{f.return_1w:.2%}</td>"
                f"<td>{f.return_1m:.2%}</td>"
                f"<td>{f.return_3m:.2%}</td>"
                f"<td>{f.vs_vnindex_1m:+.2%}</td></tr>\n"
            )

        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>EziStock Factor Snapshot - {getattr(data, 'report_date', '')}</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; }}
h1 {{ color: #1a1a2e; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: right; }}
th {{ background: #1a1a2e; color: white; }}
.footer {{ margin-top: 40px; font-size: 0.8em; color: #666; }}
</style></head><body>
<h1>📊 EziStock Weekly Factor Snapshot</h1>
<p>Report Date: {getattr(data, 'report_date', 'N/A')}</p>
<p>VNINDEX: 1W={getattr(data, 'vnindex_return_1w', 0):.2%}, 1M={getattr(data, 'vnindex_return_1m', 0):.2%}</p>
<table>
<tr><th>Factor</th><th>1W</th><th>1M</th><th>3M</th><th>vs VNINDEX</th></tr>
{rows}
</table>
<p>Top factor: {getattr(data, 'top_factor', 'N/A')} | Worst: {getattr(data, 'worst_factor', 'N/A')}</p>
<div class="footer">
<p>Generated by EziStock AI Service. This is not financial advice.</p>
</div>
</body></html>"""

    def _render_sector_deepdive_html(self, data: Any) -> str:
        """Render sector deep-dive as HTML."""
        rows = ""
        for s in getattr(data, "sectors", []):
            picks = ", ".join(p.symbol for p in s.top_picks[:3]) if s.top_picks else "—"
            rows += (
                f"<tr><td>{s.sector_name}</td>"
                f"<td>{s.return_1m:.2%}</td>"
                f"<td>{s.return_3m:.2%}</td>"
                f"<td>{s.median_pe:.1f}</td>"
                f"<td>{s.foreign_flow_trend}</td>"
                f"<td>{picks}</td></tr>\n"
            )

        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>EziStock Sector Deep-Dive - {getattr(data, 'report_date', '')}</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; }}
h1 {{ color: #1a1a2e; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: right; }}
th {{ background: #1a1a2e; color: white; }}
td:first-child {{ text-align: left; }}
.footer {{ margin-top: 40px; font-size: 0.8em; color: #666; }}
</style></head><body>
<h1>🏭 EziStock Monthly Sector Deep-Dive</h1>
<p>Report Date: {getattr(data, 'report_date', 'N/A')}</p>
<table>
<tr><th>Sector</th><th>1M</th><th>3M</th><th>P/E</th><th>Foreign Flow</th><th>Top Picks</th></tr>
{rows}
</table>
<div class="footer">
<p>Generated by EziStock AI Service. This is not financial advice.</p>
</div>
</body></html>"""

    @staticmethod
    def _html_to_pdf(html: str) -> bytes:
        """Convert HTML to PDF bytes.

        Uses a simple approach — in production, use weasyprint:
            from weasyprint import HTML
            return HTML(string=html).write_pdf()

        For now, returns the HTML as UTF-8 bytes (PDF generation
        requires weasyprint which needs system-level dependencies).
        """
        # TODO: Install weasyprint for real PDF generation
        # For MVP, store as HTML which can be rendered by browsers
        return html.encode("utf-8")
